### Bank Note Authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.

In [1]:
!pip install scikit-learn
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install xgboost
!pip install lightgbm
!pip install catboost
!pip install imbalanced-learn
!pip install scikit-plot
!pip install shap
!pip install eli5
!pip install pdpbox
!pip install hyperopt
!pip install bayesian-optimization
!pip install optuna
!pip install mlflow
!pip install pytorch
!pip install tensorflow
!pip install keras
!pip install torch
!pip install torchvision
!pip install torchtext
!pip install transformers
!pip install sentence-transformers
!pip install pytorch-lightning
!pip install fastai
!pip install spacy
!pip install nltk
!pip install gensim
!pip install textblob
!pip install wordcloud

!pip install pickle
!pip install joblib
!pip install dill
!pip install cloudpickle

Requirement already satisfied: scikit-learn in c:\users\moham\appdata\roaming\python\python311\site-packages (1.4.1.post1)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn) (3.4.0)
Requirement already satisfied: pandas in d:\anaconda_jupyter2024\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in c:\users\moham\appdata\roaming\python\python311\site-packages (1.26.4)
Requirement already satisfied: matplotlib in c:\users\moham\appdata\roaming\python\python311\site-packages (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (4.50.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\anaconda_jupyter2024\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=8 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in d:\anaconda_jupyter2024\lib\site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\moham\appdata\roaming\python\python311\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=0.25 in d:\anaconda_jupyter2024\lib\site-packages (from seaborn) (2.1.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from seaborn) (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.50.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in d:\anaconda_jupyter2024\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: pillow>=8 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas>=0.25->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Collecting xgboost
  Downloading xgboost-2.1.4-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\moham\appdata\roaming\python\python311\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\moham\appdata\roaming\python\python311\site-packages (from xgboost) (1.12.0)
Downloading xgboost-2.1.4-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 393.8 kB/s eta 0:05:18
   ---------------------------------------- 0.1/124.9 MB 655.4 kB/s eta 0:03:11
   ---------------------------------------- 0.2/124.9 MB 1.2 MB/s eta 0:01:44
   ---------------------------------------- 0.5/124.9 MB 2.1 MB/s eta 0:01:00
   ---------------------------------------- 0.8/124.9 MB 3.0 MB/s eta 0:00:42
   ---------------------------------------- 1.3/124.9 MB 4.0 MB/s eta 0:00:31
    --------------------------------------- 1.9/124.9 MB 5.0 MB/s eta 0:00:25
    --------------------------------------- 2.4/124.9 MB 5.8 MB/s eta 0:00:22
    --------------------------------------- 3.0/124.9 MB 6.4 MB/s eta 0:00:20
   - -------------------------------------- 3.5/124.9 MB 6.8 MB/s eta 0:00:18
   - -------------------------------------- 4.1/124.9 MB 7.3 MB/s eta 0:00:17
   - -------------------------------------- 4.6/124.9 MB 7.6 MB/s eta 0:00:16
   - -------------------------------------- 5.2/124.9 MB 7.9 MB/s eta 0:00:16
   - -------------------------------------- 5.7/124.9 MB 8.3 MB/s eta 0:00:15
   -- ------------------------------------- 6.3/124.9 MB 8.4 MB/s eta 0:00:15
   -- ------------------------------------- 6.9/124.9 MB 8.6 MB/s eta 0:00:14
   -- ------------------------------------- 7.4/124.9 MB 8.9 MB/s eta 0:00:14
   -- ------------------------------------- 7.9/124.9 MB 9.1 MB/s eta 0:00:13
   -- ------------------------------------- 8.5/124.9 MB 9.2 MB/s eta 0:00:13
   -- ------------------------------------- 9.0/124.9 MB 9.3 MB/s eta 0:00:13
   --- ------------------------------------ 9.6/124.9 MB 9.4 MB/s eta 0:00:13
   --- ------------------------------------ 9.9/124.9 MB 9.4 MB/s eta 0:00:13
   --- ------------------------------------ 9.9/124.9 MB 9.4 MB/s eta 0:00:13
   --- ------------------------------------ 9.9/124.9 MB 9.4 MB/s eta 0:00:13
   --- ------------------------------------ 10.4/124.9 MB 9.9 MB/s eta 0:00:12
   --- ------------------------------------ 12.3/124.9 MB 11.9 MB/s eta 0:00:10
   ---- ----------------------------------- 12.9/124.9 MB 11.9 MB/s eta 0:00:10
   ---- ----------------------------------- 13.4/124.9 MB 11.9 MB/s eta 0:00:10
   ---- ----------------------------------- 14.0/124.9 MB 11.9 MB/s eta 0:00:10
   ---- ----------------------------------- 14.5/124.9 MB 11.9 MB/s eta 0:00:10
   ---- ----------------------------------- 15.1/124.9 MB 11.9 MB/s eta 0:00:10
   ----- ---------------------------------- 15.7/124.9 MB 11.9 MB/s eta 0:00:10
   ----- ---------------------------------- 16.2/124.9 MB 11.9 MB/s eta 0:00:10
   ----- ---------------------------------- 16.8/124.9 MB 11.9 MB/s eta 0:00:10
   ----- ---------------------------------- 17.3/124.9 MB 11.9 MB/s eta 0:00:10
   ----- ---------------------------------- 17.9/124.9 MB 11.9 MB/s eta 0:00:09
   ----- ---------------------------------- 18.4/124.9 MB 11.9 MB/s eta 0:00:09
   ------ --------------------------------- 18.9/124.9 MB 11.9 MB/s eta 0:00:09
   ------ --------------------------------- 19.5/124.9 MB 11.9 MB/s eta 0:00:09
   ------ --------------------------------- 20.0/124.9 MB 11.9 MB/s eta 0:00:09
   ------ --------------------------------- 20.6/124.9 MB 13.6 MB/s eta 0:00:08
   ------ --------------------------------- 21.1/124.9 MB 13.1 MB/s eta 0:00:08
   ------ --------------------------------- 21.7/124.9 MB 12.6 MB/s eta 0:00:09
   ------- -------------------------------- 22.3/124.9 MB 11.9 MB/s eta 0:00:09
   ------- -------------------------------- 22.5/124.9 MB 11.7 MB/s eta 0:00:09
   ------- -------------------------------- 22.5/124.9 MB 11.7 MB/s eta 0:00:09
   ------- -------------------------------- 22.5/124.9 MB 11.7 MB/s eta 0:00:09
   ------- -------------------------------- 23.1/124.9 MB 10.6 MB/s eta 0:00:10
   -------- ------------------------------- 25.0/124.9 MB 11.9 MB/s eta 0:00:09
   -------- ------------------------------- 25.5/124.9 MB 11.7 MB/s eta 0:00:09
   -------- ------------------------------- 26.1/124.9 MB 11.9 MB/s eta 0:00:09
   -------- ------------------------------- 26.6/124.9 MB 11.7 MB/s eta 0:00:09
   -------- ------------------------------- 27.1/124.9 MB 11.7 MB/s eta 0:00:09
   -------- ------------------------------- 27.6/124.9 MB 11.7 MB/s eta 0:00:09
   -------- ------------------------------- 28.0/124.9 MB 11.5 MB/s eta 0:00:09
   --------- ------------------------------ 28.5/124.9 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 29.0/124.9 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 29.5/124.9 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 30.1/124.9 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 30.6/124.9 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 31.2/124.9 MB 11.3 MB/s eta 0:00:09
   ---------- ----------------------------- 31.7/124.9 MB 11.5 MB/s eta 0:00:09
   ---------- ----------------------------- 32.3/124.9 MB 11.3 MB/s eta 0:00:09
   ---------- ----------------------------- 32.8/124.9 MB 13.1 MB/s eta 0:00:08
   ---------- ----------------------------- 33.4/124.9 MB 12.8 MB/s eta 0:00:08
   ---------- ----------------------------- 33.9/124.9 MB 12.4 MB/s eta 0:00:08
   ----------- ---------------------------- 34.5/124.9 MB 11.9 MB/s eta 0:00:08
   ----------- ---------------------------- 35.0/124.9 MB 11.3 MB/s eta 0:00:08
   ----------- ---------------------------- 35.6/124.9 MB 11.3 MB/s eta 0:00:08
   ----------- ---------------------------- 36.1/124.9 MB 11.3 MB/s eta 0:00:08
   ----------- ---------------------------- 36.7/124.9 MB 11.3 MB/s eta 0:00:08
   ----------- ---------------------------- 37.3/124.9 MB 11.3 MB/s eta 0:00:08
   ------------ --------------------------- 37.8/124.9 MB 11.5 MB/s eta 0:00:08
   ------------ --------------------------- 38.6/124.9 MB 11.7 MB/s eta 0:00:08
   ------------ --------------------------- 39.1/124.9 MB 11.7 MB/s eta 0:00:08
   ------------ --------------------------- 39.6/124.9 MB 11.9 MB/s eta 0:00:08
   ------------ --------------------------- 40.2/124.9 MB 11.9 MB/s eta 0:00:08
   ------------- -------------------------- 40.8/124.9 MB 11.7 MB/s eta 0:00:08
   ------------- -------------------------- 41.3/124.9 MB 11.7 MB/s eta 0:00:08
   ------------- -------------------------- 41.9/124.9 MB 11.7 MB/s eta 0:00:08
   ------------- -------------------------- 42.4/124.9 MB 11.7 MB/s eta 0:00:08
   ------------- -------------------------- 43.0/124.9 MB 11.7 MB/s eta 0:00:08
   ------------- -------------------------- 43.6/124.9 MB 11.7 MB/s eta 0:00:07
   -------------- ------------------------- 44.1/124.9 MB 11.7 MB/s eta 0:00:07
   -------------- ------------------------- 44.6/124.9 MB 11.7 MB/s eta 0:00:07
   -------------- ------------------------- 45.2/124.9 MB 11.7 MB/s eta 0:00:07
   -------------- ------------------------- 45.8/124.9 MB 11.7 MB/s eta 0:00:07
   -------------- ------------------------- 46.3/124.9 MB 11.7 MB/s eta 0:00:07
   --------------- ------------------------ 46.9/124.9 MB 11.9 MB/s eta 0:00:07
   --------------- ------------------------ 47.4/124.9 MB 11.9 MB/s eta 0:00:07
   --------------- ------------------------ 48.0/124.9 MB 11.9 MB/s eta 0:00:07
   --------------- ------------------------ 48.5/124.9 MB 11.7 MB/s eta 0:00:07
   --------------- ------------------------ 49.1/124.9 MB 11.7 MB/s eta 0:00:07
   --------------- ------------------------ 49.7/124.9 MB 11.7 MB/s eta 0:00:07
   ---------------- ----------------------- 50.2/124.9 MB 11.7 MB/s eta 0:00:07
   ---------------- ----------------------- 50.8/124.9 MB 11.7 MB/s eta 0:00:07
   ---------------- ----------------------- 51.3/124.9 MB 11.7 MB/s eta 0:00:07
   ---------------- ----------------------- 51.9/124.9 MB 11.7 MB/s eta 0:00:07
   ---------------- ----------------------- 52.4/124.9 MB 11.7 MB/s eta 0:00:07
   ---------------- ----------------------- 53.0/124.9 MB 11.7 MB/s eta 0:00:07
   ----------------- ---------------------- 53.5/124.9 MB 11.7 MB/s eta 0:00:07
   ----------------- ---------------------- 54.1/124.9 MB 11.7 MB/s eta 0:00:07
   ----------------- ---------------------- 54.6/124.9 MB 11.9 MB/s eta 0:00:06
   ----------------- ---------------------- 55.2/124.9 MB 11.9 MB/s eta 0:00:06
   ----------------- ---------------------- 55.7/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------ --------------------- 56.3/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------ --------------------- 56.9/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------ --------------------- 57.4/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------ --------------------- 58.0/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------ --------------------- 58.5/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------ --------------------- 59.1/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------- -------------------- 59.6/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------- -------------------- 60.1/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------- -------------------- 60.7/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------- -------------------- 61.3/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------- -------------------- 61.8/124.9 MB 11.9 MB/s eta 0:00:06
   ------------------- -------------------- 62.4/124.9 MB 11.9 MB/s eta 0:00:06
   -------------------- ------------------- 62.9/124.9 MB 11.9 MB/s eta 0:00:06
   -------------------- ------------------- 63.5/124.9 MB 11.9 MB/s eta 0:00:06
   -------------------- ------------------- 64.1/124.9 MB 11.9 MB/s eta 0:00:06
   -------------------- ------------------- 64.6/124.9 MB 11.9 MB/s eta 0:00:06
   -------------------- ------------------- 65.1/124.9 MB 11.9 MB/s eta 0:00:06
   --------------------- ------------------ 65.7/124.9 MB 11.9 MB/s eta 0:00:05
   --------------------- ------------------ 66.3/124.9 MB 11.9 MB/s eta 0:00:05
   --------------------- ------------------ 66.8/124.9 MB 11.9 MB/s eta 0:00:05
   --------------------- ------------------ 67.4/124.9 MB 11.9 MB/s eta 0:00:05
   --------------------- ------------------ 67.9/124.9 MB 11.9 MB/s eta 0:00:05
   --------------------- ------------------ 68.5/124.9 MB 11.9 MB/s eta 0:00:05
   ---------------------- ----------------- 69.0/124.9 MB 11.9 MB/s eta 0:00:05
   ---------------------- ----------------- 69.6/124.9 MB 11.9 MB/s eta 0:00:05
   ---------------------- ----------------- 70.2/124.9 MB 11.9 MB/s eta 0:00:05
   ---------------------- ----------------- 70.7/124.9 MB 11.9 MB/s eta 0:00:05
   ---------------------- ----------------- 71.3/124.9 MB 11.9 MB/s eta 0:00:05
   ----------------------- ---------------- 71.8/124.9 MB 11.9 MB/s eta 0:00:05
   ----------------------- ---------------- 72.4/124.9 MB 11.9 MB/s eta 0:00:05
   ----------------------- ---------------- 72.9/124.9 MB 11.9 MB/s eta 0:00:05
   ----------------------- ---------------- 73.5/124.9 MB 11.9 MB/s eta 0:00:05
   ----------------------- ---------------- 74.1/124.9 MB 11.9 MB/s eta 0:00:05
   ----------------------- ---------------- 74.5/124.9 MB 11.9 MB/s eta 0:00:05
   ------------------------ --------------- 75.0/124.9 MB 11.7 MB/s eta 0:00:05
   ------------------------ --------------- 75.5/124.9 MB 11.7 MB/s eta 0:00:05
   ------------------------ --------------- 76.0/124.9 MB 11.7 MB/s eta 0:00:05
   ------------------------ --------------- 76.6/124.9 MB 11.7 MB/s eta 0:00:05
   ------------------------ --------------- 77.2/124.9 MB 11.7 MB/s eta 0:00:05
   ------------------------ --------------- 77.7/124.9 MB 11.7 MB/s eta 0:00:05
   ------------------------- -------------- 78.3/124.9 MB 11.7 MB/s eta 0:00:04
   ------------------------- -------------- 78.8/124.9 MB 11.7 MB/s eta 0:00:04
   ------------------------- -------------- 79.4/124.9 MB 11.7 MB/s eta 0:00:04
   ------------------------- -------------- 79.7/124.9 MB 11.7 MB/s eta 0:00:04
   ------------------------- -------------- 79.7/124.9 MB 11.7 MB/s eta 0:00:04
   ------------------------- -------------- 79.7/124.9 MB 11.7 MB/s eta 0:00:04
   ------------------------- -------------- 80.3/124.9 MB 10.2 MB/s eta 0:00:05
   -------------------------- ------------- 81.8/124.9 MB 11.3 MB/s eta 0:00:04
   -------------------------- ------------- 82.3/124.9 MB 11.1 MB/s eta 0:00:04
   -------------------------- ------------- 82.9/124.9 MB 11.1 MB/s eta 0:00:04
   -------------------------- ------------- 83.4/124.9 MB 11.1 MB/s eta 0:00:04
   -------------------------- ------------- 84.0/124.9 MB 11.1 MB/s eta 0:00:04
   --------------------------- ------------ 84.5/124.9 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 85.1/124.9 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 85.7/124.9 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 86.2/124.9 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 86.8/124.9 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 87.3/124.9 MB 11.3 MB/s eta 0:00:04
   ---------------------------- ----------- 87.9/124.9 MB 11.3 MB/s eta 0:00:04
   ---------------------------- ----------- 88.4/124.9 MB 11.3 MB/s eta 0:00:04
   ---------------------------- ----------- 89.0/124.9 MB 11.3 MB/s eta 0:00:04
   ---------------------------- ----------- 89.5/124.9 MB 11.3 MB/s eta 0:00:04
   ---------------------------- ----------- 90.1/124.9 MB 13.4 MB/s eta 0:00:03
   ----------------------------- ---------- 90.6/124.9 MB 13.1 MB/s eta 0:00:03
   ----------------------------- ---------- 91.2/124.9 MB 12.6 MB/s eta 0:00:03
   ----------------------------- ---------- 91.7/124.9 MB 12.1 MB/s eta 0:00:03
   ----------------------------- ---------- 92.3/124.9 MB 11.9 MB/s eta 0:00:03
   ----------------------------- ---------- 92.8/124.9 MB 11.9 MB/s eta 0:00:03
   ----------------------------- ---------- 93.4/124.9 MB 11.9 MB/s eta 0:00:03
   ------------------------------ --------- 93.9/124.9 MB 11.9 MB/s eta 0:00:03
   ------------------------------ --------- 94.5/124.9 MB 11.9 MB/s eta 0:00:03
   ------------------------------ --------- 95.0/124.9 MB 11.9 MB/s eta 0:00:03

  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\moham\AppData\Local\Temp\pip-install-rwo3s74v\pytorch_365ae3a81159498cb372d7ea7c183d33\setup.py", line 15, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
ERROR: Could not build wheels for pytorch, which is required to install pyproject.toml-based projects

Collecting tensorflow
  Downloading tensorflow-2.19.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in d:\anaconda_jupyter2024\lib\site-packages (from tensorflow) (23.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (4.25.3)
Requirement already satisfied: requests<3,>=2.21.0 in d:\anaconda_jupyter2024\lib\site-packages (from tensorflow) (2.31.0)
Requirement already satisfied: setuptools in d:\anaconda_jupyter2024\lib\site-packages (from tensorflow) (68.2.2)
Requirement already satisfied: six>=1.12.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in d:\anaconda_jupyter2024\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (1.62.1)
Collecting tensorboard~=2.19.0 (from tensorflow)
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.5.0 (from tensorflow)
  Downloading keras-3.9.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (1.26.4)
Collecting h5py>=3.11.0 (from tensorflow)
  Downloading h5py-3.13.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting ml-dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.1-cp311-cp311-win_amd64.whl.metadata (22 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorflow) (0.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in d:\anaconda_jupyter2024\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.41.2)
Requirement already satisfied: rich in c:\users\moham\appdata\roaming\python\python311\site-packages (from keras>=3.5.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in c:\users\moham\appdata\roaming\python\python311\site-packages (from keras>=3.5.0->tensorflow) (0.0.7)
Requirement already satisfied: optree in c:\users\moham\appdata\roaming\python\python311\site-packages (from keras>=3.5.0->tensorflow) (0.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2024.2.2)
Requirement already satisfied: markdown>=2.6.8 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorboard~=2.19.0->tensorflow) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from rich->keras>=3.5.0->tensorflow) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Downloading tensorflow-2.19.0-cp311-cp311-win_amd64.whl (375.9 MB)
   ---------------------------------------- 0.0/375.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/375.9 MB 991.0 kB/s eta 0:06:20
   ---------------------------------------- 0.2/375.9 MB 1.7 MB/s eta 0:03:36
   ---------------------------------------- 0.4/375.9 MB 2.9 MB/s eta 0:02:12
   ---------------------------------------- 0.7/375.9 MB 3.9 MB/s eta 0:01:36
   ---------------------------------------- 1.3/375.9 MB 5.6 MB/s eta 0:01:07
   ---------------------------------------- 1.9/375.9 MB 6.7 MB/s eta 0:00:57
   ---------------------------------------- 2.4/375.9 MB 7.4 MB/s eta 0:00:51
   ---------------------------------------- 2.7/375.9 MB 7.9 MB/s eta 0:00:48
   ---------------------------------------- 3.5/375.9 MB 8.3 MB/s eta 0:00:45
   ---------------------------------------- 4.1/375.9 MB 8.7 MB/s eta 0:00:43
   ---------------------------------------- 4.6/375.9 MB 9.0 MB/s eta 0:00:42
    --------------------------------------- 5.2/375.9 MB 9.2 MB/s eta 0:00:41
    --------------------------------------- 5.8/375.9 MB 9.4 MB/s eta 0:00:40
    --------------------------------------- 6.3/375.9 MB 9.6 MB/s eta 0:00:39
    --------------------------------------- 6.9/375.9 MB 9.7 MB/s eta 0:00:38
    --------------------------------------- 7.4/375.9 MB 9.9 MB/s eta 0:00:38
    --------------------------------------- 8.0/375.9 MB 10.0 MB/s eta 0:00:37
    --------------------------------------- 8.5/375.9 MB 10.1 MB/s eta 0:00:37
    --------------------------------------- 9.1/375.9 MB 10.2 MB/s eta 0:00:37
   - -------------------------------------- 9.6/375.9 MB 10.3 MB/s eta 0:00:36
   - -------------------------------------- 10.2/375.9 MB 10.3 MB/s eta 0:00:36
   - -------------------------------------- 10.7/375.9 MB 11.7 MB/s eta 0:00:32
   - -------------------------------------- 11.3/375.9 MB 11.7 MB/s eta 0:00:32
   - -------------------------------------- 11.8/375.9 MB 11.7 MB/s eta 0:00:32
   - -------------------------------------- 12.4/375.9 MB 11.9 MB/s eta 0:00:31
   - -------------------------------------- 13.0/375.9 MB 11.7 MB/s eta 0:00:32
   - -------------------------------------- 13.5/375.9 MB 11.9 MB/s eta 0:00:31
   - -------------------------------------- 14.0/375.9 MB 11.9 MB/s eta 0:00:31
   - -------------------------------------- 14.6/375.9 MB 11.9 MB/s eta 0:00:31
   - -------------------------------------- 14.8/375.9 MB 11.7 MB/s eta 0:00:31
   - -------------------------------------- 14.8/375.9 MB 11.7 MB/s eta 0:00:31
   - -------------------------------------- 14.8/375.9 MB 11.7 MB/s eta 0:00:31
   - -------------------------------------- 15.4/375.9 MB 10.6 MB/s eta 0:00:35
   - -------------------------------------- 17.4/375.9 MB 11.9 MB/s eta 0:00:31
   - -------------------------------------- 17.9/375.9 MB 11.7 MB/s eta 0:00:31
   - -------------------------------------- 18.5/375.9 MB 11.7 MB/s eta 0:00:31
   -- ------------------------------------- 19.0/375.9 MB 11.9 MB/s eta 0:00:31
   -- ------------------------------------- 19.6/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 20.1/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 20.7/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 21.2/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 21.8/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 22.3/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 22.9/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 23.4/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 24.0/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 24.6/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 25.1/375.9 MB 14.2 MB/s eta 0:00:25
   -- ------------------------------------- 25.7/375.9 MB 13.6 MB/s eta 0:00:26
   -- ------------------------------------- 26.2/375.9 MB 13.1 MB/s eta 0:00:27
   -- ------------------------------------- 26.8/375.9 MB 12.6 MB/s eta 0:00:28
   -- ------------------------------------- 27.3/375.9 MB 11.9 MB/s eta 0:00:30
   -- ------------------------------------- 27.9/375.9 MB 11.9 MB/s eta 0:00:30
   --- ------------------------------------ 28.4/375.9 MB 11.9 MB/s eta 0:00:30
   --- ------------------------------------ 29.0/375.9 MB 11.9 MB/s eta 0:00:30
   --- ------------------------------------ 29.5/375.9 MB 11.9 MB/s eta 0:00:30
   --- ------------------------------------ 30.1/375.9 MB 11.9 MB/s eta 0:00:30
   --- ------------------------------------ 30.7/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 31.2/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 31.8/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 32.3/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 32.9/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 33.4/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 34.0/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 34.5/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 35.1/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 35.6/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 36.2/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 36.7/375.9 MB 11.9 MB/s eta 0:00:29
   --- ------------------------------------ 37.3/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 37.9/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 38.4/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 39.0/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 39.5/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 40.1/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 40.6/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 41.2/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 41.7/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 42.3/375.9 MB 11.9 MB/s eta 0:00:29
   ---- ----------------------------------- 42.9/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 43.4/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 44.0/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 44.5/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 45.1/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 45.6/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 46.2/375.9 MB 11.9 MB/s eta 0:00:28
   ---- ----------------------------------- 46.8/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 47.3/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 47.9/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 48.4/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 49.0/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 49.6/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 49.7/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 49.7/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 49.7/375.9 MB 11.9 MB/s eta 0:00:28
   ----- ---------------------------------- 50.5/375.9 MB 10.6 MB/s eta 0:00:31
   ----- ---------------------------------- 51.7/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 52.3/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 52.8/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 53.3/375.9 MB 11.1 MB/s eta 0:00:30
   ----- ---------------------------------- 53.9/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 54.5/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 55.0/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 55.6/375.9 MB 11.3 MB/s eta 0:00:29
   ----- ---------------------------------- 56.2/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 56.7/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 57.3/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 57.8/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 58.4/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 58.9/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 59.5/375.9 MB 11.3 MB/s eta 0:00:29
   ------ --------------------------------- 60.0/375.9 MB 13.1 MB/s eta 0:00:25
   ------ --------------------------------- 60.6/375.9 MB 12.8 MB/s eta 0:00:25
   ------ --------------------------------- 61.1/375.9 MB 12.4 MB/s eta 0:00:26
   ------ --------------------------------- 61.7/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 62.2/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 62.8/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 63.3/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 63.9/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 64.4/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 65.0/375.9 MB 11.9 MB/s eta 0:00:27
   ------ --------------------------------- 65.5/375.9 MB 11.9 MB/s eta 0:00:27
   ------- -------------------------------- 66.1/375.9 MB 11.9 MB/s eta 0:00:27
   ------- -------------------------------- 66.7/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 67.2/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 67.8/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 68.3/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 68.9/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 69.4/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 70.0/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 70.5/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 71.1/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 71.6/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 72.2/375.9 MB 11.7 MB/s eta 0:00:26
   ------- -------------------------------- 72.7/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 73.3/375.9 MB 11.7 MB/s eta 0:00:26
   ------- -------------------------------- 73.8/375.9 MB 11.9 MB/s eta 0:00:26
   ------- -------------------------------- 74.4/375.9 MB 11.7 MB/s eta 0:00:26
   ------- -------------------------------- 74.9/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 75.5/375.9 MB 11.9 MB/s eta 0:00:26
   -------- ------------------------------- 76.0/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 76.6/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 77.2/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 77.7/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 78.3/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 78.8/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 79.4/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 79.9/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 80.5/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 81.0/375.9 MB 11.9 MB/s eta 0:00:25
   -------- ------------------------------- 81.6/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 82.2/375.9 MB 11.9 MB/s eta 0:00:25
   -------- ------------------------------- 82.7/375.9 MB 11.9 MB/s eta 0:00:25
   -------- ------------------------------- 83.3/375.9 MB 11.7 MB/s eta 0:00:26
   -------- ------------------------------- 83.8/375.9 MB 11.9 MB/s eta 0:00:25
   -------- ------------------------------- 84.4/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 84.9/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 85.5/375.9 MB 11.9 MB/s eta 0:00:25
   --------- ------------------------------ 86.0/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 86.6/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 87.1/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 87.7/375.9 MB 11.9 MB/s eta 0:00:25
   --------- ------------------------------ 88.2/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 88.8/375.9 MB 11.9 MB/s eta 0:00:25
   --------- ------------------------------ 89.3/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 89.9/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 90.3/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 90.8/375.9 MB 11.5 MB/s eta 0:00:25
   --------- ------------------------------ 91.4/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 91.9/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 92.0/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 92.0/375.9 MB 11.7 MB/s eta 0:00:25
   --------- ------------------------------ 93.3/375.9 MB 11.5 MB/s eta 0:00:25
   ---------- ----------------------------- 94.1/375.9 MB 11.7 MB/s eta 0:00:25
   ---------- ----------------------------- 94.7/375.9 MB 11.7 MB/s eta 0:00:25
   ---------- ----------------------------- 95.2/375.9 MB 11.7 MB/s eta 0:00:25
   ---------- ----------------------------- 95.8/375.9 MB 11.7 MB/s eta 0:00:24
   ---------- ----------------------------- 96.3/375.9 MB 11.7 MB/s eta 0:00:24
   ---------- ----------------------------- 96.9/375.9 MB 11.7 MB/s eta 0:00:24
   ---------- ----------------------------- 97.4/375.9 MB 11.7 MB/s eta 0:00:24

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.17.2 requires torch==2.2.2, but you have torch 2.6.0 which is incompatible.
torchaudio 2.2.2+cu121 requires torch==2.2.2+cu121, but you have torch 2.6.0 which is incompatible.

Requirement already satisfied: transformers in d:\anaconda_jupyter2024\lib\site-packages (4.40.2)
Requirement already satisfied: filelock in c:\users\moham\appdata\roaming\python\python311\site-packages (from transformers) (3.13.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (0.23.0)
Requirement already satisfied: numpy>=1.17 in c:\users\moham\appdata\roaming\python\python311\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (2023.10.3)
Requirement already satisfied: requests in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in d:\anaconda_jupyter2024\lib\site-packages (from transformers) (4.65.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (2024.3.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda_jupyter2024\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (4.12.2)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda_jupyter2024\lib\site-packages (from requests->transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda_jupyter2024\lib\site-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda_jupyter2024\lib\site-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda_jupyter2024\lib\site-packages (from requests->transformers) (2024.2.2)
Collecting sentence-transformers
  Downloading sentence_transformers-3.4.1-py3-none-any.whl.metadata (10 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
     ---------------------------------------- 0.0/44.0 kB ? eta -:--:--
     --------- ------------------------------ 10.2/44.0 kB ? eta -:--:--
     -------------------------- ----------- 30.7/44.0 kB 325.1 kB/s eta 0:00:01
     -------------------------------------- 44.0/44.0 kB 359.4 kB/s eta 0:00:00
Requirement already satisfied: tqdm in d:\anaconda_jupyter2024\lib\site-packages (from sentence-transformers) (4.65.0)
Requirement already satisfied: torch>=1.11.0 in d:\anaconda_jupyter2024\lib\site-packages (from sentence-transformers) (2.6.0)
Requirement already satisfied: scikit-learn in c:\users\moham\appdata\roaming\python\python311\site-packages (from sentence-transformers) (1.4.1.post1)
Requirement already satisfied: scipy in c:\users\moham\appdata\roaming\python\python311\site-packages (from sentence-transformers) (1.12.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in d:\anaconda_jupyter2024\lib\site-packages (from sentence-transformers) (0.23.0)
Requirement already satisfied: Pillow in c:\users\moham\appdata\roaming\python\python311\site-packages (from sentence-transformers) (10.3.0)
Requirement already satisfied: filelock in c:\users\moham\appdata\roaming\python\python311\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.3.1)
Requirement already satisfied: packaging>=20.9 in d:\anaconda_jupyter2024\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda_jupyter2024\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in d:\anaconda_jupyter2024\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.31.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda_jupyter2024\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: networkx in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.3)
Collecting sympy==1.13.1 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-0.29.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\moham\appdata\roaming\python\python311\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda_jupyter2024\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2023.10.3)
Collecting tokenizers<0.22,>=0.21 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: safetensors>=0.4.1 in d:\anaconda_jupyter2024\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn->sentence-transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn->sentence-transformers) (3.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda_jupyter2024\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda_jupyter2024\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda_jupyter2024\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda_jupyter2024\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.2.2)
Downloading sentence_transformers-3.4.1-py3-none-any.whl (275 kB)
   ---------------------------------------- 0.0/275.9 kB ? eta -:--:--
   -------- ------------------------------- 61.4/275.9 kB 1.7 MB/s eta 0:00:01
   ----------------------------- ---------- 204.8/275.9 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 275.9/275.9 kB 2.1 MB/s eta 0:00:00
Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.4/10.0 MB 11.6 MB/s eta 0:00:01
   --- ------------------------------------ 0.9/10.0 MB 11.7 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/10.0 MB 11.8 MB/s eta 0:00:01
   -------- ------------------------------- 2.0/10.0 MB 11.7 MB/s eta 0:00:01
   ---------- ----------------------------- 2.6/10.0 MB 11.7 MB/s eta 0:00:01
   ------------ --------------------------- 3.1/10.0 MB 11.8 MB/s eta 0:00:01
   -------------- ------------------------- 3.7/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/10.0 MB 11.8 MB/s eta 0:00:01
   ------------------- -------------------- 4.8/10.0 MB 11.8 MB/s eta 0:00:01
   --------------------- ------------------ 5.3/10.0 MB 11.8 MB/s eta 0:00:01
   ----------------------- ---------------- 5.9/10.0 MB 11.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.4/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/10.0 MB 11.8 MB/s eta 0:00:01
   ------------------------------ --------- 7.5/10.0 MB 11.8 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.6/10.0 MB 11.8 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  9.8/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 9.8 MB/s eta 0:00:00
Downloading huggingface_hub-0.29.3-py3-none-any.whl (468 kB)
   ---------------------------------------- 0.0/469.0 kB ? eta -:--:--
   --------------------------------------  460.8/469.0 kB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 469.0/469.0 kB 9.8 MB/s eta 0:00:00
Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 15.7 MB/s eta 0:00:01
   ----------------- ---------------------- 1.1/2.4 MB 13.5 MB/s eta 0:00:01
   -------------------------- ------------- 1.6/2.4 MB 12.9 MB/s eta 0:00:01
   ----------------------------------- ---- 2.2/2.4 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------  2.4/2.4 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 9.7 MB/s eta 0:00:00
Installing collected packages: sympy, huggingface-hub, tokenizers, transformers, sentence-transformers
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.23.0
    Uninstalling huggingface-hub-0.23.0:
      Successfully uninstalled huggingface-hub-0.23.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.40.2
    Uninstalling transformers-4.40.2:
      Successfully uninstalled transformers-4.40.2
Successfully installed huggingface-hub-0.29.3 sentence-transformers-3.4.1 sympy-1.13.1 tokenizers-0.21.1 transformers-4.49.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.2+cu121 requires torch==2.2.2+cu121, but you have torch 2.6.0 which is incompatible.

Collecting pytorch-lightning
  Downloading pytorch_lightning-2.5.0.post0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: torch>=2.1.0 in d:\anaconda_jupyter2024\lib\site-packages (from pytorch-lightning) (2.6.0)
Requirement already satisfied: tqdm>=4.57.0 in d:\anaconda_jupyter2024\lib\site-packages (from pytorch-lightning) (4.65.0)
Requirement already satisfied: PyYAML>=5.4 in d:\anaconda_jupyter2024\lib\site-packages (from pytorch-lightning) (6.0.1)
Requirement already satisfied: fsspec>=2022.5.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning) (2024.3.1)
Collecting torchmetrics>=0.7.0 (from pytorch-lightning)
  Downloading torchmetrics-1.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: packaging>=20.0 in d:\anaconda_jupyter2024\lib\site-packages (from pytorch-lightning) (23.1)
Requirement already satisfied: typing-extensions>=4.4.0 in d:\anaconda_jupyter2024\lib\site-packages (from pytorch-lightning) (4.12.2)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning)
  Downloading lightning_utilities-0.14.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in d:\anaconda_jupyter2024\lib\site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning) (3.9.3)
Requirement already satisfied: setuptools in d:\anaconda_jupyter2024\lib\site-packages (from lightning-utilities>=0.10.0->pytorch-lightning) (68.2.2)
Requirement already satisfied: filelock in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch>=2.1.0->pytorch-lightning) (3.13.3)
Requirement already satisfied: networkx in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch>=2.1.0->pytorch-lightning) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch>=2.1.0->pytorch-lightning) (3.1.3)
Requirement already satisfied: sympy==1.13.1 in d:\anaconda_jupyter2024\lib\site-packages (from torch>=2.1.0->pytorch-lightning) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from sympy==1.13.1->torch>=2.1.0->pytorch-lightning) (1.3.0)
Requirement already satisfied: numpy>1.20.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from torchmetrics>=0.7.0->pytorch-lightning) (1.26.4)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from tqdm>=4.57.0->pytorch-lightning) (0.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in d:\anaconda_jupyter2024\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in d:\anaconda_jupyter2024\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\anaconda_jupyter2024\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\anaconda_jupyter2024\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\anaconda_jupyter2024\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (1.9.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from jinja2->torch>=2.1.0->pytorch-lightning) (2.1.5)
Requirement already satisfied: idna>=2.0 in d:\anaconda_jupyter2024\lib\site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (2.10)
Downloading pytorch_lightning-2.5.0.post0-py3-none-any.whl (819 kB)
   ---------------------------------------- 0.0/819.3 kB ? eta -:--:--
   - -------------------------------------- 30.7/819.3 kB 1.4 MB/s eta 0:00:01
   ----- ---------------------------------- 122.9/819.3 kB 1.4 MB/s eta 0:00:01
   --------------- ------------------------ 317.4/819.3 kB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 686.1/819.3 kB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 819.3/819.3 kB 4.0 MB/s eta 0:00:00
Downloading lightning_utilities-0.14.0-py3-none-any.whl (28 kB)
Downloading torchmetrics-1.6.3-py3-none-any.whl (931 kB)
   ---------------------------------------- 0.0/931.7 kB ? eta -:--:--
   ----------------------- --------------- 553.0/931.7 kB 17.5 MB/s eta 0:00:01
   --------------------------------------  921.6/931.7 kB 14.7 MB/s eta 0:00:01
   ---------------------------------------- 931.7/931.7 kB 9.8 MB/s eta 0:00:00
Installing collected packages: lightning-utilities, torchmetrics, pytorch-lightning
Successfully installed lightning-utilities-0.14.0 pytorch-lightning-2.5.0.post0 torchmetrics-1.6.3
Collecting fastai
  Downloading fastai-2.7.19-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: pip in d:\anaconda_jupyter2024\lib\site-packages (from fastai) (23.3.1)
Requirement already satisfied: packaging in d:\anaconda_jupyter2024\lib\site-packages (from fastai) (23.1)
Collecting fastdownload<2,>=0.0.5 (from fastai)
  Downloading fastdownload-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Collecting fastcore<1.8,>=1.5.29 (from fastai)
  Downloading fastcore-1.7.29-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: torchvision>=0.11 in c:\users\moham\appdata\roaming\python\python311\site-packages (from fastai) (0.17.2)
Requirement already satisfied: matplotlib in c:\users\moham\appdata\roaming\python\python311\site-packages (from fastai) (3.8.3)
Requirement already satisfied: pandas in d:\anaconda_jupyter2024\lib\site-packages (from fastai) (2.1.4)
Requirement already satisfied: requests in d:\anaconda_jupyter2024\lib\site-packages (from fastai) (2.31.0)
Requirement already satisfied: pyyaml in d:\anaconda_jupyter2024\lib\site-packages (from fastai) (6.0.1)
Collecting fastprogress>=0.2.4 (from fastai)
  Downloading fastprogress-1.0.3-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pillow>=9.0.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from fastai) (10.3.0)
Requirement already satisfied: scikit-learn in c:\users\moham\appdata\roaming\python\python311\site-packages (from fastai) (1.4.1.post1)
Requirement already satisfied: scipy in c:\users\moham\appdata\roaming\python\python311\site-packages (from fastai) (1.12.0)
Collecting spacy<4 (from fastai)
  Downloading spacy-3.8.4-cp311-cp311-win_amd64.whl.metadata (27 kB)
Requirement already satisfied: torch<2.7,>=1.10 in d:\anaconda_jupyter2024\lib\site-packages (from fastai) (2.6.0)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy<4->fastai)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy<4->fastai)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy<4->fastai)
  Downloading murmurhash-1.0.12-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy<4->fastai)
  Downloading cymem-2.0.11-cp311-cp311-win_amd64.whl.metadata (8.8 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy<4->fastai)
  Downloading preshed-3.0.9-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy<4->fastai)
  Downloading thinc-8.3.4-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy<4->fastai)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy<4->fastai)
  Downloading srsly-2.5.1-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy<4->fastai)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy<4->fastai)
  Downloading weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy<4->fastai)
  Downloading typer-0.15.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy<4->fastai) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from spacy<4->fastai) (1.26.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in d:\anaconda_jupyter2024\lib\site-packages (from spacy<4->fastai) (1.10.12)
Requirement already satisfied: jinja2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from spacy<4->fastai) (3.1.3)
Requirement already satisfied: setuptools in d:\anaconda_jupyter2024\lib\site-packages (from spacy<4->fastai) (68.2.2)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<4->fastai)
  Downloading langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda_jupyter2024\lib\site-packages (from requests->fastai) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda_jupyter2024\lib\site-packages (from requests->fastai) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda_jupyter2024\lib\site-packages (from requests->fastai) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda_jupyter2024\lib\site-packages (from requests->fastai) (2024.2.2)
Requirement already satisfied: filelock in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch<2.7,>=1.10->fastai) (3.13.3)
Requirement already satisfied: typing-extensions>=4.10.0 in d:\anaconda_jupyter2024\lib\site-packages (from torch<2.7,>=1.10->fastai) (4.12.2)
Requirement already satisfied: networkx in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch<2.7,>=1.10->fastai) (3.2.1)
Requirement already satisfied: fsspec in c:\users\moham\appdata\roaming\python\python311\site-packages (from torch<2.7,>=1.10->fastai) (2024.3.1)
Requirement already satisfied: sympy==1.13.1 in d:\anaconda_jupyter2024\lib\site-packages (from torch<2.7,>=1.10->fastai) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from sympy==1.13.1->torch<2.7,>=1.10->fastai) (1.3.0)
Collecting torch<2.7,>=1.10 (from fastai)
  Using cached torch-2.2.2-cp311-cp311-win_amd64.whl.metadata (26 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->fastai) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->fastai) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->fastai) (4.50.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->fastai) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->fastai) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->fastai) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas->fastai) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas->fastai) (2023.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn->fastai) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from scikit-learn->fastai) (3.4.0)
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy<4->fastai)
  Downloading language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib->fastai) (1.16.0)
Collecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy<4->fastai)
  Downloading blis-1.2.0-cp311-cp311-win_amd64.whl.metadata (7.9 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy<4->fastai)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy<4->fastai) (0.4.6)
Requirement already satisfied: click>=8.0.0 in d:\anaconda_jupyter2024\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (8.1.7)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy<4->fastai)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=10.11.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (13.7.1)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy<4->fastai)
  Downloading cloudpathlib-0.21.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in d:\anaconda_jupyter2024\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from jinja2->spacy<4->fastai) (2.1.5)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<4->fastai)
  Downloading marisa_trie-1.2.1-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4->fastai) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4->fastai) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4->fastai) (0.1.2)
Downloading fastai-2.7.19-py3-none-any.whl (234 kB)
   ---------------------------------------- 0.0/234.8 kB ? eta -:--:--
   --------------- ------------------------ 92.2/234.8 kB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 225.3/234.8 kB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 234.8/234.8 kB 2.0 MB/s eta 0:00:00
Downloading fastcore-1.7.29-py3-none-any.whl (84 kB)
   ---------------------------------------- 0.0/84.2 kB ? eta -:--:--
   ---------------------------------------- 84.2/84.2 kB ? eta 0:00:00
Downloading fastdownload-0.0.7-py3-none-any.whl (12 kB)
Downloading fastprogress-1.0.3-py3-none-any.whl (12 kB)
Downloading spacy-3.8.4-cp311-cp311-win_amd64.whl (12.2 MB)
   ---------------------------------------- 0.0/12.2 MB ? eta -:--:--
    --------------------------------------- 0.3/12.2 MB 9.2 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/12.2 MB 10.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/12.2 MB 11.1 MB/s eta 0:00:01
   ------ --------------------------------- 2.0/12.2 MB 11.4 MB/s eta 0:00:01
   -------- ------------------------------- 2.5/12.2 MB 11.6 MB/s eta 0:00:01
   ---------- ----------------------------- 3.1/12.2 MB 11.6 MB/s eta 0:00:01
   ----------- ---------------------------- 3.6/12.2 MB 11.6 MB/s eta 0:00:01
   ------------- -------------------------- 4.2/12.2 MB 11.6 MB/s eta 0:00:01
   ---------------- ----------------------- 5.1/12.2 MB 11.6 MB/s eta 0:00:01
   ------------------ --------------------- 5.7/12.2 MB 11.7 MB/s eta 0:00:01
   -------------------- ------------------- 6.2/12.2 MB 11.7 MB/s eta 0:00:01
   ---------------------- ----------------- 6.8/12.2 MB 11.7 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.2 MB 11.7 MB/s eta 0:00:01
   ------------------------- -------------- 7.8/12.2 MB 11.6 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.2 MB 11.7 MB/s eta 0:00:01
   ----------------------------- ---------- 9.0/12.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------- -------- 9.5/12.2 MB 11.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.1/12.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------- ----- 10.6/12.2 MB 11.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.2/12.2 MB 11.9 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  12.2/12.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  12.2/12.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  12.2/12.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  12.2/12.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 12.2/12.2 MB 9.6 MB/s eta 0:00:00
Using cached torch-2.2.2-cp311-cp311-win_amd64.whl (198.6 MB)
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.11-cp311-cp311-win_amd64.whl (39 kB)
Downloading langcodes-3.5.0-py3-none-any.whl (182 kB)
   ---------------------------------------- 0.0/183.0 kB ? eta -:--:--
   --------------------------------------- 183.0/183.0 kB 10.8 MB/s eta 0:00:00
Downloading murmurhash-1.0.12-cp311-cp311-win_amd64.whl (25 kB)
Downloading preshed-3.0.9-cp311-cp311-win_amd64.whl (122 kB)
   ---------------------------------------- 0.0/122.3 kB ? eta -:--:--
   ---------------------------------------- 122.3/122.3 kB 7.0 MB/s eta 0:00:00
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.1-cp311-cp311-win_amd64.whl (632 kB)
   ---------------------------------------- 0.0/632.6 kB ? eta -:--:--
   ----------------------------------- --- 583.7/632.6 kB 12.5 MB/s eta 0:00:01
   --------------------------------------- 632.6/632.6 kB 10.0 MB/s eta 0:00:00
Downloading thinc-8.3.4-cp311-cp311-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ----------------- ---------------------- 0.6/1.5 MB 13.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.2/1.5 MB 12.7 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 10.6 MB/s eta 0:00:00
Downloading typer-0.15.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.1 kB ? eta -:--:--
   ---------------------------------------- 45.1/45.1 kB 2.3 MB/s eta 0:00:00
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.1-py3-none-any.whl (50 kB)
   ---------------------------------------- 0.0/50.3 kB ? eta -:--:--
   ---------------------------------------- 50.3/50.3 kB 2.7 MB/s eta 0:00:00
Downloading blis-1.2.0-cp311-cp311-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.2 MB 10.5 MB/s eta 0:00:01
   ------ --------------------------------- 1.1/6.2 MB 11.2 MB/s eta 0:00:01
   ---------- ----------------------------- 1.6/6.2 MB 11.3 MB/s eta 0:00:01
   -------------- ------------------------- 2.2/6.2 MB 11.5 MB/s eta 0:00:01
   ----------------- ---------------------- 2.7/6.2 MB 11.6 MB/s eta 0:00:01
   --------------------- ------------------ 3.3/6.2 MB 11.7 MB/s eta 0:00:01
   ------------------------ --------------- 3.9/6.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------- ----------- 4.4/6.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------- -------- 4.9/6.2 MB 11.7 MB/s eta 0:00:01
   ----------------------------------- ---- 5.5/6.2 MB 11.7 MB/s eta 0:00:01

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.2+cu121 requires torch==2.2.2+cu121, but you have torch 2.2.2 which is incompatible.
torchtext 0.18.0 requires torch>=2.3.0, but you have torch 2.2.2 which is incompatible.

Requirement already satisfied: spacy in d:\anaconda_jupyter2024\lib\site-packages (3.8.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (1.10.12)
Requirement already satisfied: jinja2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from spacy) (3.1.3)
Requirement already satisfied: setuptools in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (68.2.2)
Requirement already satisfied: packaging>=20.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (23.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in d:\anaconda_jupyter2024\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in d:\anaconda_jupyter2024\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in d:\anaconda_jupyter2024\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda_jupyter2024\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.2.2)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in d:\anaconda_jupyter2024\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.2.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in d:\anaconda_jupyter2024\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in d:\anaconda_jupyter2024\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in d:\anaconda_jupyter2024\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.7.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in d:\anaconda_jupyter2024\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in d:\anaconda_jupyter2024\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from jinja2->spacy) (2.1.5)
Requirement already satisfied: marisa-trie>=1.1.0 in d:\anaconda_jupyter2024\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: nltk in d:\anaconda_jupyter2024\lib\site-packages (3.8.1)
Requirement already satisfied: click in d:\anaconda_jupyter2024\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\moham\appdata\roaming\python\python311\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in d:\anaconda_jupyter2024\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in d:\anaconda_jupyter2024\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: gensim in d:\anaconda_jupyter2024\lib\site-packages (4.3.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from gensim) (1.12.0)
Requirement already satisfied: smart-open>=1.8.1 in d:\anaconda_jupyter2024\lib\site-packages (from gensim) (5.2.1)
Collecting FuzzyTM>=0.4.0 (from gensim)
  Downloading FuzzyTM-2.0.9-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: pandas in d:\anaconda_jupyter2024\lib\site-packages (from FuzzyTM>=0.4.0->gensim) (2.1.4)
Collecting pyfume (from FuzzyTM>=0.4.0->gensim)
  Downloading pyFUME-0.3.4-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moham\appdata\roaming\python\python311\site-packages (from pandas->FuzzyTM>=0.4.0->gensim) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas->FuzzyTM>=0.4.0->gensim) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\anaconda_jupyter2024\lib\site-packages (from pandas->FuzzyTM>=0.4.0->gensim) (2023.3)
Collecting scipy>=1.7.0 (from gensim)
  Downloading scipy-1.10.1-cp311-cp311-win_amd64.whl.metadata (58 kB)
     ---------------------------------------- 0.0/59.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.0 kB ? eta -:--:--
     -------------------------------- ----- 51.2/59.0 kB 650.2 kB/s eta 0:00:01
     -------------------------------------- 59.0/59.0 kB 624.8 kB/s eta 0:00:00
Collecting numpy>=1.18.5 (from gensim)
  Downloading numpy-1.24.4-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting simpful==2.12.0 (from pyfume->FuzzyTM>=0.4.0->gensim)
  Downloading simpful-2.12.0-py3-none-any.whl.metadata (4.8 kB)
Collecting fst-pso==1.8.1 (from pyfume->FuzzyTM>=0.4.0->gensim)
  Downloading fst-pso-1.8.1.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pandas (from FuzzyTM>=0.4.0->gensim)
  Downloading pandas-1.5.3-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting miniful (from fst-pso==1.8.1->pyfume->FuzzyTM>=0.4.0->gensim)
  Downloading miniful-0.0.6.tar.gz (2.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six>=1.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas->FuzzyTM>=0.4.0->gensim) (1.16.0)
Downloading FuzzyTM-2.0.9-py3-none-any.whl (31 kB)
Downloading pyFUME-0.3.4-py3-none-any.whl (60 kB)
   ---------------------------------------- 0.0/60.3 kB ? eta -:--:--
   ---------------------------------------- 60.3/60.3 kB 3.3 MB/s eta 0:00:00
Downloading numpy-1.24.4-cp311-cp311-win_amd64.whl (14.8 MB)
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/14.8 MB 3.5 MB/s eta 0:00:05
   - -------------------------------------- 0.5/14.8 MB 4.7 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.8 MB 6.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.5/14.8 MB 8.0 MB/s eta 0:00:02
   ----- ---------------------------------- 2.1/14.8 MB 8.9 MB/s eta 0:00:02
   ------- -------------------------------- 2.6/14.8 MB 9.3 MB/s eta 0:00:02
   -------- ------------------------------- 3.2/14.8 MB 9.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.7/14.8 MB 10.0 MB/s eta 0:00:02
   ----------- ---------------------------- 4.3/14.8 MB 10.2 MB/s eta 0:00:02
   ------------- -------------------------- 4.9/14.8 MB 10.3 MB/s eta 0:00:01
   -------------- ------------------------- 5.4/14.8 MB 10.5 MB/s eta 0:00:01
   ---------------- ----------------------- 6.0/14.8 MB 10.6 MB/s eta 0:00:01
   ----------------- ---------------------- 6.5/14.8 MB 10.7 MB/s eta 0:00:01
   ------------------ --------------------- 7.0/14.8 MB 10.7 MB/s eta 0:00:01
   -------------------- ------------------- 7.6/14.8 MB 10.7 MB/s eta 0:00:01
   --------------------- ------------------ 8.1/14.8 MB 10.8 MB/s eta 0:00:01
   ----------------------- ---------------- 8.6/14.8 MB 10.8 MB/s eta 0:00:01
   ------------------------ --------------- 9.1/14.8 MB 10.8 MB/s eta 0:00:01
   -------------------------- ------------- 9.7/14.8 MB 10.9 MB/s eta 0:00:01
   --------------------------- ------------ 10.2/14.8 MB 10.9 MB/s eta 0:00:01
   ----------------------------- ---------- 10.8/14.8 MB 11.7 MB/s eta 0:00:01
   ------------------------------ --------- 11.3/14.8 MB 11.7 MB/s eta 0:00:01
   ------------------------------- -------- 11.6/14.8 MB 11.7 MB/s eta 0:00:01
   -------------------------------- ------- 12.0/14.8 MB 11.5 MB/s eta 0:00:01
   -------------------------------- ------- 12.0/14.8 MB 11.5 MB/s eta 0:00:01
   ----------------------------------- ---- 13.0/14.8 MB 10.9 MB/s eta 0:00:01
   ------------------------------------ --- 13.6/14.8 MB 11.1 MB/s eta 0:00:01
   -------------------------------------- - 14.1/14.8 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  14.7/14.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------- 14.8/14.8 MB 8.7 MB/s eta 0:00:00
Downloading scipy-1.10.1-cp311-cp311-win_amd64.whl (42.2 MB)
   ---------------------------------------- 0.0/42.2 MB ? eta -:--:--
    --------------------------------------- 0.6/42.2 MB 17.8 MB/s eta 0:00:03
   - -------------------------------------- 1.1/42.2 MB 14.4 MB/s eta 0:00:03
   - -------------------------------------- 1.7/42.2 MB 13.4 MB/s eta 0:00:04
   -- ------------------------------------- 2.2/42.2 MB 13.0 MB/s eta 0:00:04
   -- ------------------------------------- 2.8/42.2 MB 12.7 MB/s eta 0:00:04
   --- ------------------------------------ 3.3/42.2 MB 12.6 MB/s eta 0:00:04
   --- ------------------------------------ 3.9/42.2 MB 12.5 MB/s eta 0:00:04
   ---- ----------------------------------- 4.5/42.2 MB 12.4 MB/s eta 0:00:04
   ---- ----------------------------------- 5.0/42.2 MB 12.3 MB/s eta 0:00:04
   ----- ---------------------------------- 5.5/42.2 MB 12.2 MB/s eta 0:00:04
   ----- ---------------------------------- 6.1/42.2 MB 12.2 MB/s eta 0:00:03
   ------ --------------------------------- 6.6/42.2 MB 12.1 MB/s eta 0:00:03
   ------ --------------------------------- 7.2/42.2 MB 12.1 MB/s eta 0:00:03
   ------- -------------------------------- 7.7/42.2 MB 12.1 MB/s eta 0:00:03
   ------- -------------------------------- 8.3/42.2 MB 12.1 MB/s eta 0:00:03
   -------- ------------------------------- 8.9/42.2 MB 12.1 MB/s eta 0:00:03
   -------- ------------------------------- 9.4/42.2 MB 12.0 MB/s eta 0:00:03
   --------- ------------------------------ 10.0/42.2 MB 12.0 MB/s eta 0:00:03
   --------- ------------------------------ 10.5/42.2 MB 11.9 MB/s eta 0:00:03
   ---------- ----------------------------- 11.1/42.2 MB 11.9 MB/s eta 0:00:03
   ----------- ---------------------------- 11.6/42.2 MB 11.9 MB/s eta 0:00:03
   ----------- ---------------------------- 12.2/42.2 MB 11.9 MB/s eta 0:00:03
   ------------ --------------------------- 12.7/42.2 MB 11.9 MB/s eta 0:00:03
   ------------ --------------------------- 13.3/42.2 MB 11.9 MB/s eta 0:00:03
   ------------- -------------------------- 13.9/42.2 MB 11.9 MB/s eta 0:00:03
   ------------- -------------------------- 14.4/42.2 MB 11.9 MB/s eta 0:00:03
   -------------- ------------------------- 15.0/42.2 MB 11.9 MB/s eta 0:00:03
   -------------- ------------------------- 15.5/42.2 MB 11.9 MB/s eta 0:00:03
   --------------- ------------------------ 16.0/42.2 MB 11.9 MB/s eta 0:00:03
   --------------- ------------------------ 16.6/42.2 MB 11.9 MB/s eta 0:00:03
   ---------------- ----------------------- 17.2/42.2 MB 11.9 MB/s eta 0:00:03
   ---------------- ----------------------- 17.7/42.2 MB 11.9 MB/s eta 0:00:03
   ----------------- ---------------------- 18.2/42.2 MB 11.9 MB/s eta 0:00:03
   ----------------- ---------------------- 18.8/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------ --------------------- 19.4/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------ --------------------- 19.9/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------- -------------------- 20.5/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------- -------------------- 21.0/42.2 MB 11.9 MB/s eta 0:00:02
   -------------------- ------------------- 21.6/42.2 MB 11.9 MB/s eta 0:00:02
   -------------------- ------------------- 22.1/42.2 MB 11.9 MB/s eta 0:00:02
   --------------------- ------------------ 22.7/42.2 MB 11.9 MB/s eta 0:00:02
   --------------------- ------------------ 23.2/42.2 MB 11.9 MB/s eta 0:00:02
   ---------------------- ----------------- 23.8/42.2 MB 11.9 MB/s eta 0:00:02
   ----------------------- ---------------- 24.4/42.2 MB 11.9 MB/s eta 0:00:02
   ----------------------- ---------------- 24.9/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------------ --------------- 25.4/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------------ --------------- 26.0/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------------- -------------- 26.5/42.2 MB 11.9 MB/s eta 0:00:02
   ------------------------- -------------- 27.1/42.2 MB 11.9 MB/s eta 0:00:02
   -------------------------- ------------- 27.6/42.2 MB 11.9 MB/s eta 0:00:02
   -------------------------- ------------- 28.2/42.2 MB 11.9 MB/s eta 0:00:02
   --------------------------- ------------ 28.8/42.2 MB 11.9 MB/s eta 0:00:02
   --------------------------- ------------ 29.3/42.2 MB 11.9 MB/s eta 0:00:02
   ---------------------------- ----------- 29.9/42.2 MB 11.9 MB/s eta 0:00:02
   ---------------------------- ----------- 30.4/42.2 MB 11.9 MB/s eta 0:00:01
   ----------------------------- ---------- 31.0/42.2 MB 11.9 MB/s eta 0:00:01
   ----------------------------- ---------- 31.5/42.2 MB 11.9 MB/s eta 0:00:01
   ------------------------------ --------- 32.1/42.2 MB 11.9 MB/s eta 0:00:01
   ------------------------------ --------- 32.6/42.2 MB 11.9 MB/s eta 0:00:01
   ------------------------------- -------- 33.2/42.2 MB 11.9 MB/s eta 0:00:01
   ------------------------------- -------- 33.7/42.2 MB 11.9 MB/s eta 0:00:01
   -------------------------------- ------- 34.3/42.2 MB 11.9 MB/s eta 0:00:01
   --------------------------------- ------ 34.9/42.2 MB 11.9 MB/s eta 0:00:01
   --------------------------------- ------ 35.4/42.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------- ----- 36.0/42.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------- ----- 36.5/42.2 MB 11.7 MB/s eta 0:00:01
   ----------------------------------- ---- 37.1/42.2 MB 11.9 MB/s eta 0:00:01
   ----------------------------------- ---- 37.6/42.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------------ --- 38.2/42.2 MB 11.9 MB/s eta 0:00:01
   ------------------------------------ --- 38.7/42.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------------- -- 39.3/42.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------------- -- 39.8/42.2 MB 11.7 MB/s eta 0:00:01
   -------------------------------------- - 40.3/42.2 MB 11.9 MB/s eta 0:00:01
   -------------------------------------- - 40.9/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  41.5/42.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  42.0/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.2/42.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 42.2/42.2 MB 6.7 MB/s eta 0:00:00
Downloading pandas-1.5.3-cp311-cp311-win_amd64.whl (10.3 MB)
   ---------------------------------------- 0.0/10.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.3 MB 10.9 MB/s eta 0:00:01
   ---- ----------------------------------- 1.1/10.3 MB 11.4 MB/s eta 0:00:01
   ------ --------------------------------- 1.6/10.3 MB 11.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.2/10.3 MB 11.7 MB/s eta 0:00:01
   ---------- ----------------------------- 2.8/10.3 MB 11.7 MB/s eta 0:00:01
   ------------ --------------------------- 3.3/10.3 MB 11.7 MB/s eta 0:00:01
   -------------- ------------------------- 3.8/10.3 MB 11.6 MB/s eta 0:00:01
   ----------------- ---------------------- 4.4/10.3 MB 11.7 MB/s eta 0:00:01
   ------------------- -------------------- 4.9/10.3 MB 11.7 MB/s eta 0:00:01
   --------------------- ------------------ 5.5/10.3 MB 11.6 MB/s eta 0:00:01
   ----------------------- ---------------- 6.0/10.3 MB 11.7 MB/s eta 0:00:01
   ------------------------- -------------- 6.6/10.3 MB 11.7 MB/s eta 0:00:01

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bayesian-optimization 2.0.3 requires numpy>=1.25, but you have numpy 1.24.4 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 1.24.4 which is incompatible.
torchtext 0.18.0 requires torch>=2.3.0, but you have torch 2.2.2 which is incompatible.

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Collecting nltk>=3.9 (from textblob)
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click in d:\anaconda_jupyter2024\lib\site-packages (from nltk>=3.9->textblob) (8.1.7)
Requirement already satisfied: joblib in c:\users\moham\appdata\roaming\python\python311\site-packages (from nltk>=3.9->textblob) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in d:\anaconda_jupyter2024\lib\site-packages (from nltk>=3.9->textblob) (2023.10.3)
Requirement already satisfied: tqdm in d:\anaconda_jupyter2024\lib\site-packages (from nltk>=3.9->textblob) (4.65.0)
Requirement already satisfied: colorama in d:\anaconda_jupyter2024\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
    --------------------------------------- 10.2/624.3 kB ? eta -:--:--
   - ------------------------------------- 30.7/624.3 kB 435.7 kB/s eta 0:00:02
   --- ----------------------------------- 61.4/624.3 kB 544.7 kB/s eta 0:00:02
   -------- ----------------------------- 133.1/624.3 kB 871.5 kB/s eta 0:00:01
   ----------------- ---------------------- 276.5/624.3 kB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 583.7/624.3 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 624.3/624.3 kB 2.3 MB/s eta 0:00:00
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------- ------------------------ 0.6/1.5 MB 18.5 MB/s eta 0:00:01
   ------------------------------ --------- 1.1/1.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 13.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 9.6 MB/s eta 0:00:00
Installing collected packages: nltk, textblob
  Attempting uninstall: nltk
    Found existing installation: nltk 3.8.1
    Uninstalling nltk-3.8.1:
      Successfully uninstalled nltk-3.8.1
Successfully installed nltk-3.9.1 textblob-0.19.0
Collecting wordcloud
  Downloading wordcloud-1.9.4-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.6.1 in d:\anaconda_jupyter2024\lib\site-packages (from wordcloud) (1.24.3)
Requirement already satisfied: pillow in c:\users\moham\appdata\roaming\python\python311\site-packages (from wordcloud) (10.3.0)
Requirement already satisfied: matplotlib in c:\users\moham\appdata\roaming\python\python311\site-packages (from wordcloud) (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (4.50.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (1.4.5)
Requirement already satisfied: packaging>=20.0 in d:\anaconda_jupyter2024\lib\site-packages (from matplotlib->wordcloud) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\moham\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\moham\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Downloading wordcloud-1.9.4-cp311-cp311-win_amd64.whl (299 kB)
   ---------------------------------------- 0.0/299.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/299.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/299.9 kB ? eta -:--:--
   ----- --------------------------------- 41.0/299.9 kB 279.3 kB/s eta 0:00:01
   ----------- --------------------------- 92.2/299.9 kB 581.0 kB/s eta 0:00:01
   ----------------------- -------------- 184.3/299.9 kB 926.0 kB/s eta 0:00:01
   ---------------------------------------  297.0/299.9 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 299.9/299.9 kB 1.2 MB/s eta 0:00:00
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.4

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

Requirement already satisfied: joblib in c:\users\moham\appdata\roaming\python\python311\site-packages (1.3.2)
Requirement already satisfied: dill in d:\anaconda_jupyter2024\lib\site-packages (0.3.7)
Requirement already satisfied: cloudpickle in d:\anaconda_jupyter2024\lib\site-packages (2.2.1)

In [2]:
##Dataset Link: https://www.kaggle.com/ritesaluja/bank-note-authentication-uci-data
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('BankNote_Authentication.csv')

In [4]:
df

      variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [5]:
### Independent and Dependent features
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
X.head()

   variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [7]:
y.head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: class, dtype: int64

In [8]:
### Train Test Split
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [11]:
### Implement Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
## Prediction
y_pred=classifier.predict(X_test)

In [13]:
### Check Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

In [14]:
score

0.9878640776699029

In [15]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("classifier.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

In [16]:
import numpy as np

In [17]:
classifier.predict([[2,3,4,1]])

C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)